### ISSUE TITLE
Complementando o df_translation.csv

### ISSUE THREAD

**Issue by Welinson** [TioFuna/DF-Brasil-Hook#1]
Eu vi que estavam usando apenas usando o hardcoded_steam.pot nas traduções, então resolvi incluir o  objects.pot e text_set.pot no arquivo CSV, não foi difícil, simplesmente criei um arquivo .POT usando os 3 e dele criei o CSV, inclusive consertei diversos erros no código do objects.pot que impossibilitava a tradução de metais.

Apenas para finalizar, usei o Visual code para editar o CSV com a codificação ISO 8859-2

[df_translation.csv](https://github.com/TioFuna/DF-Brasil-Hook/files/10300460/df_translation.csv)

**Comment by TioFuna** [comment]
Legal @Welinson , mas a principio esse outros textos podem ser traduzidos simplesmente trocando os arquivos do jogo. O que tornaria mais confiável. Mas pra facilitar, esta forma que vc utilizou tbm pode ser usada, não testei pra dizer se roda bem. É uma opção também.
Obrigado pela ajuda, e entre lá no Discord pra facilitar a comunicação e colaborar com a comunidade.
