### ISSUE TITLE
Ao usar a tradução não é possível cortar arvores.

### ISSUE THREAD

**Issue by jhudsonsg** [TioFuna/DF-Brasil-Hook#2]
- Não sei se é só comigo kkkk, mas fiz a instalação seguindo os passos, mas toda vez que uso a tradução não é possível cortar as arvores.

**Comment by Welinson** [comment]
Entra no discord https://discord.gg/mJ97nYbQ para acompanhar a tradução mais de perto

**Comment by TioFuna** [comment]
Obrigado por relatar o seu erro.
Estamos achando vários erros, pois traduziram coisas que não eram pra traduzir lá no Transifex.
Estamos caçando esses erros. E conforme vamos arrumando, vamos disponibilizando aqui e no Discord novas atualizações.

**Comment by jhudsonsg** [comment]
Show, vou entrar no discord então pra acompanhar mais de perto.

**Comment by jhudsonsg** [comment]
Verifiquei a ultima atualização e percebi que foi corrigido o erro eu reportei.
